baseURL = "https://dominicp6.github.io/TheHumbleScientists/"
languageCode = "en-us"
title = "The Humble Scientists"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "The Humble Scientists - All rights reserved"
enableEmoji = true
publishDir = "docs"
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  logo = "/images/brain.jpg"
  description ="Musings in AI-based drug discovery and other somewhat sciency things"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "The Humble Scientists"
  thumbnail = "/images/brain.jpg"
  description = ""

[params.index]
  picture = "/images/brain.jpg"
  title = "The Humble Scientists"
  subtitle = "Musings in AI-based drug discovery and other somewhat sciency things"
  mdtext = '''
'''
  alertbar = false

[params.social]
  github = "<username>"
  linkedin = "<username>"
  xing = "<username>"
  medium = "<username>"
  twitter = "<username>"
  instagram = "<username>"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/"
